apiVersion: v1
kind: Service
metadata:
  labels:
    app: mavenproject
  name: mavenproject-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: mavenproject
  sessionAffinity: None
  type: NodePort
